const specializations = [
    { value: "", label: "" },
    { value: "Cardiology", label: "Cardiology" },
    { value: "Dermatology", label: "Dermatology" },
    { value: "Neurology", label: "Neurology" },
    { value: "Pediatrics", label: "Pediatrics" },
    { value: "Orthopedics", label: "Orthopedics" },
    { value: "Gastroenterology", label: "Gastroenterology" },
    { value: "Oncology", label: "Oncology" },
    { value: "Ophthalmology", label: "Ophthalmology" },
    { value: "Radiology", label: "Radiology" },
    { value: "Psychiatry", label: "Psychiatry" },
    { value: "Obstetrics and Gynecology", label: "Obstetrics and Gynecology" },
    { value: "Urology", label: "Urology" },
    { value: "Endocrinology", label: "Endocrinology" },
    { value: "Rheumatology", label: "Rheumatology" },
    { value: "Pulmonology", label: "Pulmonology" },
    { value: "Nephrology", label: "Nephrology" },
    { value: "Otolaryngology", label: "Otolaryngology" },
    { value: "Geriatrics", label: "Geriatrics" },
    { value: "Infectious Diseases", label: "Infectious Diseases" },
    { value: "Allergy and Immunology", label: "Allergy and Immunology" },
    { value: "Physical Medicine and Rehabilitation", label: "Physical Medicine and Rehabilitation" },
    { value: "Anesthesiology", label: "Anesthesiology" },
    { value: "Emergency Medicine", label: "Emergency Medicine" },
    { value: "Critical Care Medicine", label: "Critical Care Medicine" },
    { value: "Hematology", label: "Hematology" },
    { value: "Pathology", label: "Pathology" },
    { value: "Plastic Surgery", label: "Plastic Surgery" },
    { value: "Vascular Surgery", label: "Vascular Surgery" },
    { value: "Trauma Surgery", label: "Trauma Surgery" },
    { value: "Transplant Surgery", label: "Transplant Surgery" },
    { value: "Bariatric Surgery", label: "Bariatric Surgery" },
    { value: "Reproductive Endocrinology and Infertility", label: "Reproductive Endocrinology and Infertility" },
    { value: "Maternal-Fetal Medicine", label: "Maternal-Fetal Medicine" },
    { value: "Neonatology", label: "Neonatology" },
    { value: "Palliative Care", label: "Palliative Care" },
    { value: "Sleep Medicine", label: "Sleep Medicine" },
    { value: "Addiction Medicine", label: "Addiction Medicine" },
    { value: "Sports Medicine", label: "Sports Medicine" },
    { value: "Genetics", label: "Genetics" },
    { value: "Preventive Medicine", label: "Preventive Medicine" },
    { value: "Occupational Medicine", label: "Occupational Medicine" },
    { value: "Aerospace Medicine", label: "Aerospace Medicine" },
    { value: "Hospice and Palliative Medicine", label: "Hospice and Palliative Medicine" },
    { value: "Pain Medicine", label: "Pain Medicine" },
    { value: "Nuclear Medicine", label: "Nuclear Medicine" },
    { value: "Radiation Oncology", label: "Radiation Oncology" },
    { value: "Interventional Radiology", label: "Interventional Radiology" },
    { value: "Diagnostic Radiology", label: "Diagnostic Radiology" }
  ];
  
  export default specializations;